# -*- coding: utf-8 -*-
"""latihan python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hr5ilmhdXsiSn8plXdNR9zfvLNuyMZkt
"""

#maximum antara 2 angka
def max_of_two(x,y):
  if x > y:
    return x
  return y

#maximum dari 3 angka
def max_of_three(x,y,z):
  return max_of_two(x, max_of_two(y,z))

#maximum dari 4 angka
def max_of_four(x,y,z,a):
  return max_of_two(x, max_of_three(y,z,a))

#maximum dari banyak angka dalam list
def max_of_list(list):
  max_num = list[0]

  for num in list:
    if num > max_num:
      max_num = num

  return max_num

maks_4 = max_of_four(32,44,12,77)
print(maks_4)

angka = [1,2,4,6,7,4,55,67,77,3,21,13,15,34,65,91,65,34,55]
maksimum = max_of_list(angka)
print(maksimum)

#multiply number int in list
def multiply(nums):
  total = 1
  for x in nums:
    total = total*x

  return total

numbers = [1,2,3,4]
print(multiply(numbers))

#Cek dan menjumlahkan huruf kapital dalam suatu string
def How_Upper(string):
  d = {"UPPER_CASE": 0, "LOWER_CASE": 0}
  for c in string:
    if c.isupper():
      d["UPPER_CASE"] += 1
    elif c.islower():
      d["LOWER_CASE"] += 1
    else:
      pass
  print(f'jumlah huruf kapitalnya adalah {d["UPPER_CASE"]}')
  print(f'jumlah huruf non kapitalnya adalah {d["LOWER_CASE"]}')

How_Upper("Robert Gunanta Bukit")

#Kalkulator Simulasi Pembiayaan Aplikasi Home Credit
def credit(harga, dp, tenor):
    bunga = 0.039
    pokok = harga - dp
    cicilan = pokok / tenor
    cicilan_bunga = pokok * bunga / tenor
    cicilan_per_bulan = cicilan + cicilan_bunga
    print("Perhitungan ini hanya estimasi dan sudah termasuk biaya admin serta biaya bulanan.")
    print("=" * 80)
    print(f"Harga Barang: Rp {harga:,.0f}")
    print(f"DP: Rp {dp:,.0f}")
    print(f"Tenor: {tenor} bulan")
    return cicilan_per_bulan

if __name__ == "__main__":
    harga = int(input("Harga Barang: Rp "))
    dp = int(input("Jumlah Uang Muka (DP): Rp "))
    tenor = int(input("Tenor (bulan): 3 6 12 "))
    cicilan_per_bulan = credit(harga,dp,tenor)
    print(f"Hasil perhitungan\n Cicilan mulai dari Rp {cicilan_per_bulan:,.0f}")

#ex input: [12345, 12344, 12334]
#ex output: [123** ,123** ,123**]

def mask_list(numbers):
    masked = []
    for number in numbers:
        num_clean = number.strip()
        if len(num_clean) > 3:
            mask_num = num_clean[:3] + "*" * (len(num_clean) - 3)
            masked.append(mask_num)
        else:
            masked.append(number)
    return masked

if __name__ == "__main__":
    input_list = list(input("masukan daftar angka (pisahkan dengan koma): ").split(","))
    output_list = mask_list(input_list)
    print("Hasil:", output_list)

"""#### 13) Pajak Penjualan
Setiap pelanggan warung makanan dikenakan pajak 15% dari nilai pembelian. Buatlah program untuk mendapat nilai pembelian yang sebenarnya jika diketahui pelanggan membayar belanja makanan dikasir dengan nilai uang tertentu
"""

C = float(input())
# C = P + 0.15 * P
P = C/1.15
print(f"{P:.2f}")

"""#### 15) Coklat Bebek

Pak Dengklek memiliki banyak sekali bebek di kandangnya. Bebek-bebek tsb diberi nomor mulai dari 1,2, dst. Karena hari kemerdekaan bebek telah tiba, Pak Dengklek berencana utk menghadiahkan coklat untuk bebek-bebeknya. Uniknya, pak dengklek ingin agar bebek-bebknya tsb menerima jumlah coklat sesuai aturan berikut: bebek pertama mendapat 1 coklat, bebek kedua mendapat 2 coklat, bebek ketiga mendapat 3 coklat, dst. Karena keterbatasan keuangan bulan inni, pak dengklek hanya mampu membeli C buah coklat. Buat program untuk memnentukan berapa nomor bebek pertama yang tidak mendapat coklat.

"""

C = int(input("Jumlah coklat yg dibeli: "))
total = 0
for i in range(1, C + 1):
  total += i
  if total > C:
    print(f"Bebek pertama yang tidak mendapat coklat adalah nomor {i}")
    break

"""#### 14) Menukar uang ribuan

Dik lembar uang rupiah 100 ribuan, 50 ribuan, 10 ribuan, 5 ribuan, 2 ribuan, dan seribuan dalam jumlah yang tak terbatas. Jika diberikan suatu nilai uang dalam satuan rubuan, dapatkan banyaknya setiap lembar uang yang mungkin, dimulai dari nilai lembar uang terbesar hingga terkecil. Sbeagai contoh, uang 59 ribu (input 59) akan memiliki 0 lembar 100 ribuan, 1 lembar 50 ribuan, 1 lembar 5 ribuan, 2 lembar 2 ribuan, 0 lembar seribuan, maka output (0 1 0 1 2 0).
"""

n = int(input("masukkan nominal rupiah (angka selain nol saja): "))
lst_rp = []
pecahan = [100, 50, 10, 5, 2, 1]

for p in pecahan:
  lst_rp.append(n//p)
  n = n % p
print(lst_rp)